export const registerFormControls = [
  {
    name: "username",
    label: "User Name",
    placeholder: "Enter your user name",
    componentType: "input",
    type: "text",
  },
  {
    name: "email",
    label: "Email",
    placeholder: "Enter your email",
    componentType: "input",
    type: "email",
  },
  {
    name: "password",
    label: "Password",
    placeholder: "Enter your password",
    componentType: "input",
    type: "password",
  },
];

export const loginFormControls = [
  {
    name: "email",
    label: "Email",
    placeholder: "Enter your email",
    componentType: "input",
    type: "email",
  },
  {
    name: "password",
    label: "Password",
    placeholder: "Enter your password",
    componentType: "input",
    type: "password",
  },
];

export const addProductFormElements = [
  {
    label: "Title",
    name: "title",
    componentType: "input",
    type: "text",
    placeholder: "Enter product title",
  },
  {
    label: "Description",
    name: "description",
    componentType: "textarea",
    placeholder: "Enter product description",
  },
  {
    label: "Category",
    name: "category",
    componentType: "select",
    options: [
      { id: "men", label: "Men" },
      { id: "women", label: "Women" },
      { id: "kids", label: "Kids" },
      { id: "accessories", label: "Accessories" },
      { id: "footwear", label: "Footwear" },
    ],
  },
  {
    label: "Brand",
    name: "brand",
    componentType: "select",
    options: [],
  },
  {
    label: "Price",
    name: "price",
    componentType: "input",
    type: "number",
    placeholder: "Enter product price",
  },
  {
    label: "Sale Price",
    name: "salePrice",
    componentType: "input",
    type: "number",
    placeholder: "Enter sale price (optional)",
  },
  {
    label: "Total Stock",
    name: "totalStock",
    componentType: "input",
    type: "number",
    placeholder: "Enter total stock",
  },
];

export const brandsByCategory = {
  men: [
    { id: "nike", label: "Nike" },
    { id: "adidas", label: "Adidas" },
    { id: "puma", label: "Puma" },
    { id: "levi", label: "Levi's" },
    { id: "tommy", label: "Tommy Hilfiger" },
    { id: "ralph", label: "Ralph Lauren" },
    { id: "calvin", label: "Calvin Klein" },
    { id: "hugo", label: "Hugo Boss" },
    { id: "timberland", label: "Timberland" },
    { id: "gap", label: "Gap" },
  ],
  women: [
    { id: "zara", label: "Zara" },
    { id: "h&m", label: "H&M" },
    { id: "forever21", label: "Forever 21" },
    { id: "mango", label: "Mango" },
    { id: "guess", label: "Guess" },
    { id: "tommy", label: "Tommy Hilfiger" },
    { id: "calvin", label: "Calvin Klein" },
    { id: "coach", label: "Coach" },
    { id: "dior", label: "Dior" },
    { id: "uniqlo", label: "Uniqlo" },
  ],
  kids: [
    { id: "h&m", label: "H&M" },
    { id: "nike", label: "Nike" },
    { id: "adidas", label: "Adidas" },
    { id: "puma", label: "Puma" },
    { id: "gap", label: "Gap Kids" },
    { id: "next", label: "Next" },
    { id: "mothercare", label: "Mothercare" },
    { id: "primary", label: "Primary" },
  ],
  accessories: [
    { id: "nike", label: "Nike" },
    { id: "adidas", label: "Adidas" },
    { id: "fossil", label: "Fossil" },
    { id: "timex", label: "Timex" },
    { id: "coach", label: "Coach" },
    { id: "guess", label: "Guess" },
    { id: "sunglass-hut", label: "Sunglass Hut" },
    { id: "pandora", label: "Pandora" },
  ],
  footwear: [
    { id: "nike", label: "Nike" },
    { id: "adidas", label: "Adidas" },
    { id: "puma", label: "Puma" },
    { id: "timberland", label: "Timberland" },
    { id: "vans", label: "Vans" },
    { id: "converse", label: "Converse" },
    { id: "skechers", label: "Skechers" },
    { id: "birkenstock", label: "Birkenstock" },
  ],
};

export const shoppingViewHeaderMenuItems = [
  {
    id: "home",
    label: "Home",
    path: "/shop/home",
  },
  {
    id: "products",
    label: "Products",
    path: "/shop/listing",
  },
  {
    id: "men",
    label: "Men",
    path: "/shop/listing",
  },
  {
    id: "women",
    label: "Women",
    path: "/shop/listing",
  },
  {
    id: "kids",
    label: "Kids",
    path: "/shop/listing",
  },
  {
    id: "footwear",
    label: "Footwear",
    path: "/shop/listing",
  },
  {
    id: "accessories",
    label: "Accessories",
    path: "/shop/listing",
  },
  {
    id: "search",
    label: "Search",
    path: "/shop/search",
  },
];

export const categoryOptionsMap = {
  men: "Men",
  women: "Women",
  kids: "Kids",
  accessories: "Accessories",
  footwear: "Footwear",
};

export const brandOptionsMap = {
  nike: "Nike",
  adidas: "Adidas",
  puma: "Puma",
  levi: "Levi",
  zara: "Zara",
  "h&m": "H&M",
  tommy: "Tommy Hilfiger",
  ralph: "Ralph Lauren",
  calvin: "Calvin Klein",
  hugo: "Hugo Boss",
  timberland: "Timberland",
  gap: "Gap",
  forever21: "Forever 21",
  mango: "Mango",
  guess: "Guess",
  coach: "Coach",
  dior: "Dior",
  uniqlo: "Uniqlo",
  next: "Next",
  mothercare: "Mothercare",
  primary: "Primary",
  fossil: "Fossil",
  timex: "Timex",
  "sunglass-hut": "Sunglass Hut",
  pandora: "Pandora",
  vans: "Vans",
  converse: "Converse",
  skechers: "Skechers",
  birkenstock: "Birkenstock",
};

export const filterOptions = {
  category: [
    { id: "men", label: "Men" },
    { id: "women", label: "Women" },
    { id: "kids", label: "Kids" },
    { id: "accessories", label: "Accessories" },
    { id: "footwear", label: "Footwear" },
  ],
  brand: [
    { id: "nike", label: "Nike" },
    { id: "adidas", label: "Adidas" },
    { id: "puma", label: "Puma" },
    { id: "levi", label: "Levi's" },
    { id: "zara", label: "Zara" },
    { id: "h&m", label: "H&M" },
    { id: "tommy", label: "Tommy Hilfiger" },
    { id: "ralph", label: "Ralph Lauren" },
    { id: "calvin", label: "Calvin Klein" },
    { id: "hugo", label: "Hugo Boss" },
    { id: "timberland", label: "Timberland" },
    { id: "gap", label: "Gap" },
    { id: "forever21", label: "Forever 21" },
    { id: "mango", label: "Mango" },
    { id: "guess", label: "Guess" },
    { id: "coach", label: "Coach" },
    { id: "dior", label: "Dior" },
    { id: "uniqlo", label: "Uniqlo" },
    { id: "next", label: "Next" },
    { id: "mothercare", label: "Mothercare" },
    { id: "primary", label: "Primary" },
    { id: "fossil", label: "Fossil" },
    { id: "timex", label: "Timex" },
    { id: "sunglass-hut", label: "Sunglass Hut" },
    { id: "pandora", label: "Pandora" },
    { id: "vans", label: "Vans" },
    { id: "converse", label: "Converse" },
    { id: "skechers", label: "Skechers" },
    { id: "birkenstock", label: "Birkenstock" },
  ],
};

export const sortOptions = [
  { id: "price-lowtohigh", label: "Price: Low to High" },
  { id: "price-hightolow", label: "Price: High to Low" },
  { id: "title-atoz", label: "Title: A to Z" },
  { id: "title-ztoa", label: "Title: Z to A" },
];

export const countryAndCodeMap = {
  Afghanistan: "+93",
  Albania: "+355",
  Algeria: "+213",
  Andorra: "+376",
  Angola: "+244",
  Argentina: "+54",
  Armenia: "+374",
  Australia: "+61",
  Austria: "+43",
  Azerbaijan: "+994",
  Bahamas: "+1",
  Bahrain: "+973",
  Bangladesh: "+880",
  Barbados: "+1",
  Belarus: "+375",
  Belgium: "+32",
  Belize: "+501",
  Benin: "+229",
  Bhutan: "+975",
  Bolivia: "+591",
  Bosnia: "+387",
  Botswana: "+267",
  Brazil: "+55",
  Brunei: "+673",
  Bulgaria: "+359",
  "Burkina Faso": "+226",
  Burundi: "+257",
  Cambodia: "+855",
  Cameroon: "+237",
  Canada: "+1",
  "Cape Verde": "+238",
  "Central African Republic": "+236",
  Chad: "+235",
  Chile: "+56",
  China: "+86",
  Colombia: "+57",
  Comoros: "+269",
  Congo: "+242",
  "Costa Rica": "+506",
  "Côte d'Ivoire": "+225",
  Croatia: "+385",
  Cuba: "+53",
  Cyprus: "+357",
  "Czech Republic": "+420",
  Czechia: "+420",
  Denmark: "+45",
  Djibouti: "+253",
  Dominica: "+1",
  "Dominican Republic": "+1",
  Ecuador: "+593",
  Egypt: "+20",
  "El Salvador": "+503",
  "Equatorial Guinea": "+240",
  Eritrea: "+291",
  Estonia: "+372",
  Eswatini: "+268",
  Ethiopia: "+251",
  Fiji: "+679",
  Finland: "+358",
  France: "+33",
  Gabon: "+241",
  Gambia: "+220",
  Georgia: "+995",
  Germany: "+49",
  Ghana: "+233",
  Gibraltar: "+350",
  Greece: "+30",
  Grenada: "+1",
  Guatemala: "+502",
  Guinea: "+224",
  "Guinea-Bissau": "+245",
  Guyana: "+592",
  Haiti: "+509",
  Honduras: "+504",
  "Hong Kong": "+852",
  Hungary: "+36",
  Iceland: "+354",
  India: "+91",
  Indonesia: "+62",
  Iran: "+98",
  Iraq: "+964",
  Ireland: "+353",
  Israel: "+972",
  Italy: "+39",
  Jamaica: "+1",
  Japan: "+81",
  Jordan: "+962",
  Kazakhstan: "+7",
  Kenya: "+254",
  Kiribati: "+686",
  "North Korea": "+850",
  "South Korea": "+82",
  Kuwait: "+965",
  Kyrgyzstan: "+996",
  Laos: "+856",
  Latvia: "+371",
  Lebanon: "+961",
  Lesotho: "+266",
  Liberia: "+231",
  Libya: "+218",
  Liechtenstein: "+423",
  Lithuania: "+370",
  Luxembourg: "+352",
  Macao: "+853",
  Madagascar: "+261",
  Malawi: "+265",
  Malaysia: "+60",
  Maldives: "+960",
  Mali: "+223",
  Malta: "+356",
  "Marshall Islands": "+692",
  Mauritania: "+222",
  Mauritius: "+230",
  Mexico: "+52",
  Micronesia: "+691",
  Moldova: "+373",
  Monaco: "+377",
  Mongolia: "+976",
  Montenegro: "+382",
  Morocco: "+212",
  Mozambique: "+258",
  Myanmar: "+95",
  Namibia: "+264",
  Nauru: "+674",
  Nepal: "+977",
  Netherlands: "+31",
  "New Zealand": "+64",
  Nicaragua: "+505",
  Niger: "+227",
  Nigeria: "+234",
  Niue: "+683",
  "North Macedonia": "+389",
  Norway: "+47",
  Oman: "+968",
  Pakistan: "+92",
  Palau: "+680",
  Palestine: "+970",
  Panama: "+507",
  "Papua New Guinea": "+675",
  Paraguay: "+595",
  Peru: "+51",
  Philippines: "+63",
  Poland: "+48",
  Portugal: "+351",
  Qatar: "+974",
  Romania: "+40",
  Russia: "+7",
  Rwanda: "+250",
  "Saint Kitts and Nevis": "+1",
  "Saint Lucia": "+1",
  "Saint Vincent and Grenadines": "+1",
  Samoa: "+685",
  "San Marino": "+378",
  "Sao Tome and Principe": "+239",
  "Saudi Arabia": "+966",
  Senegal: "+221",
  Serbia: "+381",
  Seychelles: "+248",
  "Sierra Leone": "+232",
  Singapore: "+65",
  Slovakia: "+421",
  Slovenia: "+386",
  "Solomon Islands": "+677",
  Somalia: "+252",
  "South Africa": "+27",
  Spain: "+34",
  "Sri Lanka": "+94",
  Sudan: "+249",
  Suriname: "+597",
  Sweden: "+46",
  Switzerland: "+41",
  Syria: "+963",
  Taiwan: "+886",
  Tajikistan: "+992",
  Tanzania: "+255",
  Thailand: "+66",
  "Timor-Leste": "+670",
  Togo: "+228",
  Tonga: "+676",
  "Trinidad and Tobago": "+1",
  Tunisia: "+216",
  Turkey: "+90",
  Turkmenistan: "+993",
  Tuvalu: "+688",
  Uganda: "+256",
  Ukraine: "+380",
  "United Arab Emirates": "+971",
  "United Kingdom": "+44",
  "United States": "+1",
  Uruguay: "+598",
  Uzbekistan: "+998",
  Vanuatu: "+678",
  "Vatican City": "+379",
  Venezuela: "+58",
  Vietnam: "+84",
  "West Bank": "+970",
  "Western Sahara": "+212",
  Yemen: "+967",
  Zambia: "+260",
  Zimbabwe: "+263",
};

export const addressFormControls = [
  {
    label: "Name",
    name: "name",
    componentType: "input",
    type: "text",
    placeholder: "Enter your full name",
  },
  {
    label: "Address Line 1",
    name: "addressLine1",
    componentType: "input",
    type: "text",
    placeholder: "Enter your address (e.g., H.No. 45, Near Lake View Colony)",
  },
  {
    label: "Address Line 2",
    name: "addressLine2",
    componentType: "input",
    type: "text",
    placeholder: "Enter additional address details (e.g., MP Nagar Zone 2)",
  },
  {
    label: "City",
    name: "city",
    componentType: "input",
    type: "text",
    placeholder: "Enter your city",
  },
  {
    label: "State",
    name: "state",
    componentType: "input",
    type: "text",
    placeholder: "Enter your state",
  },
  {
    label: "PIN Code",
    name: "pincode",
    componentType: "input",
    type: "text",
    placeholder: "Enter your PIN code",
  },
  {
    label: "Country",
    name: "country",
    componentType: "select",
    options: Object.keys(countryAndCodeMap).map((country) => ({
      id: country,
      label: country,
    })),
  },
  {
    label: "Phone",
    name: "phone",
    componentType: "phone-with-country",
    countryCodeName: "countryCode",
    placeholder: "Enter your phone number",
  },
  {
    label: "Notes",
    name: "notes",
    componentType: "textarea",
    placeholder: "Enter any additional notes",
  },
];
